name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-binaries:
    strategy:
      matrix:
        runs-on: [buildjet-4vcpu-ubuntu-2204, buildjet-4vcpu-ubuntu-2204-arm]

    runs-on: ${{matrix.runs-on}}

    steps:
      - uses: actions/checkout@v3

      - id: build
        name: Building agent
        uses: docker/build-push-action@v3
        with:
          push: false

      - name: Generate SBOM from the container
        if: ${{ matrix.runs-on == 'buildjet-4vcpu-ubuntu-2204' }}
        uses: eyakubovich/sbom-action@ey/add-config-input
        with:
          image: ${{ steps.build.outputs.digest }}
          artifact-name: sbom.spdx.json
          upload-artifact: true
          config: .github/edgebit/build-syft.yaml

      - name: Save metadata to an artifact
        if: ${{ matrix.runs-on == 'buildjet-4vcpu-ubuntu-2204' }}
        run: |
          cat > /tmp/metadata.json <<EOF
            {
              "image-id": "${{ steps.build.outputs.imageid }}",
              "pr-number": "${{ github.event.number }}",
              "tags": "${{ github.ref == 'refs/heads/main' && 'latest' || '' }}"
            }
          EOF

      - uses: actions/upload-artifact@v3
        if: ${{ matrix.runs-on == 'buildjet-4vcpu-ubuntu-2204' }}
        with:
          name: metadata.json
          path: /tmp/metadata.json
