name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build-binaries:
    strategy:
      matrix:
        runs-on: [buildjet-4vcpu-ubuntu-2204, buildjet-4vcpu-ubuntu-2204-arm]

    runs-on: ${{matrix.runs-on}}

    steps:
      - uses: actions/checkout@v3

      - id: build
        name: Building agent
        uses: docker/build-push-action@v3
        with:
          push: false

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        if: ${{ matrix.runs-on == 'buildjet-4vcpu-ubuntu-2204' }}
        with:
          # generate for the container built above
          image: ${{ steps.build.outputs.imageid }}
          artifact-name: sbom.syft.json
          output-file: /tmp/sbom.syft.json
          format: syft-json

      - name: Save Artifacts
        if: ${{ matrix.runs-on == 'buildjet-4vcpu-ubuntu-2204' }}
        run: |
          mkdir -p ./artifacts
          cat > ./artifacts/metadata.json <<EOF
            {
              "image-id": "${{ steps.build.outputs.imageid }}",
              "pr-number": "${{ github.event.number }}"
            }
          EOF
          cp /tmp/sbom.syft.json ./artifacts/

      - uses: actions/upload-artifact@v2
        if: ${{ matrix.runs-on == 'buildjet-4vcpu-ubuntu-2204' }}
        with:
          name: artifacts
          path: artifacts/
